<?php

/**
 * @file
 * Collect the titles from a Feed Item nod via URL link XML/RSS feed import and display those in a block.
*/


/**
 *Implements hook_menu().
 */

function f1_feed_block_menu(){
  $items['admin/config/f1_feed_block'] = array(
    'title' => 'F1 Feed Block Settings',
    'description' => 'Administer the F1 Feed Block settings',
    'page callback' => 'drupal_get_form',
    'page arguements' => array('f1_feed_block_settings_form'),
    'access arguements' => array('manage F1 feed block settings'),
    'file' => 'f1_feed_block.admin.inc',
  );
  $items['admin/reports/f1_feed_block'] = array(
    'title' => "F1 Feed Block Posts",
    'description' => 'View all the F1 Feed imported posts.',
    'page callback' => 'f1_feed_block_posts',
    'access arguments' => array('view F1 feed block posts'),
    'file' => 'f1_feed_block.admin.inc',
  );
  return $items;
}

/**
 * Any time you wna to have a callback to an admin file or source, you will have it be
 * an admin.inc file, otherwise you'll have it go towards a pages.inc file.
 */


/**
 * Implements hook_permission().
 */

 function f1_feed_block_permission(){
   return array(
     'view f1 feed block posts' => array(
       'title' => t('View all the F1 Feed imported posts on the main F1 posts page'),
       'description' => t('View all the Formula 1 imported posts on the main posts page'),
     ),
     'change RSS feed used in f1 feed' => array(
       'title' => t('Change the RSS feed used in the Formula 1 feed'),
       'description' => t('Add new RSS feed to be imported'),
     ),
     'manage f1 feed block settings' => array(
       'title' => t('Manage Formula 1 Feed settings'),
       'description' => t('Allow user to manage the Formula 1 feed block settings'),
     ),
   );
 }

 function f1_feed_block_form_node_form_alter(&$form, $form_state, $form_id) {
    $node = $form['#node'];
    $types = variable_get('f1_feed_block_types', array());
    if ($types[$node->type]) && user_access('manage F1 feed settings')) {
      $form['f1_feed_block'] = array(
        '#title' => t("F1 Feed Block"),
        '#type' => 'fieldset',
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#group' => 'additional_settings',
      );
      $form['f1_feed_block']['f1_feed_block_enabled'] = array(
        '#title' => t("Allow this node to be posted to the F1 Block"),
        '#type' => 'checkbox',
        '#default_value' => isset($node->f1_feed_block_enabled) ? $node->f1_feed_block_enabled : FALSE,
      );
    }
 }
